In [3]:
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt

In [8]:
#Creating a NumPy Array

list = [1.6,2.2,3.1,4.89, "type"]

arr = np.array(list)
print(arr)

['1.6' '2.2' '3.1' '4.89' 'type']


In [9]:
#.dtype attribute
print(arr.dtype)

<U32


In [13]:
"""
Size Comparison of ndarray and list objects
"""

from sys import getsizeof

lst  = {1,5,2,3,23,1,23,213,2,13,123,12,3,12}  #int + object meta info
print(getsizeof(lst))

arr= np.array(lst)                             #int
print(getsizeof(arr))

728
96


In [1]:

"""
Operation with NumPy Arrays
"""

prices = [30, 25, 40, 20, 20, 35, 50, 35]

#with a list
new_prices = [price-5 for price in prices]
print(new_prices)

#with a ndarray
prices_arr = np.array(prices)
prices_arr -= 5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]


In [16]:
# 세번의 시험에 대한 각 학생 별 점수를 NumPy 배열로 선언하세요

test_1 = np.array ([92,94,88,91,87])
test_2 = np.array ([79,100,86,93,91])
test_3 = np.array ([87,85,72,90,92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed

print("\n", total_grade)

final_grade = total_grade / 3

print("\n", final_grade)

jeremy_test_2 = test_2[3]

manual_adwoa_test_1 = np.array([test_1[1],test_1[2]])

print(manual_adwoa_test_1)

student_scores  = np.array([test_1,test_2,test_3])

print(student_scores)

tanya_test_3_scores = student_scores[0][0]

print(tanya_test_3_scores)

cody_all_scores = student_scores[:,4]

print(cody_all_scores)

[89 87 74 92 94]

 [260 281 248 276 272]

 [86.66666667 93.66666667 82.66666667 92.         90.66666667]
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
92
[87 91 92]


In [22]:
"""
Logical Operations with Arrays
"""

# masking

a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

# select using Logical operations
selected = a[a > 5]
print(selected)


# combined Logical operations
selected = a[(a > 5) | (a < 3)]
print(selected)

selected = a[(a < 4) | (a > 8)]
print(selected)


[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  9  8  9  7]
[10  2  2  3  9  9]


In [25]:
"""
Exercise: Goldilocks Porridge Festival
"""

porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge<60]

hot = porridge[porridge>80]

just_right = porridge[(porridge<80) &  (porridge>60) ]

print(cold)

print(hot)

print(just_right)

[50 56 51]
[90 85 98]
[79 65 63 79]
