In [1]:
import numpy as np

In [2]:
"""
NumPy Array Attributes
"""

# Creating on array

print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [7]:
# Random number generator

np.random.seed(0)
arr1= np.random.randint(10,size=6)
print(arr1)
arr2= np.random.randint(10,size=(3,4))
print(arr2)
arr3= np.random.randint(10,size=(3,4,5))
print(arr3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [12]:
# Array Attributes

print(arr2.ndim)
print(arr2.shape) # 중요
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)
print(arr2.nbytes)


2
(3, 4)
12
int32
4
48


In [13]:
# Array Slicing 

arr = np.arange(10)

print(arr)
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [19]:
# Multi-dimensional Subarrays

arr= np.random.randint(10,size=(6,8))
print(arr)

arr_sub = arr[3:5,4:7]
print(arr_sub)


[[3 3 9 2 5 2 3 5]
 [7 2 7 1 6 5 0 0]
 [3 1 9 9 6 6 7 8]
 [8 7 0 8 6 8 9 8]
 [3 6 1 7 4 9 2 0]
 [8 2 7 8 4 4 1 7]]
[[6 8 9]
 [4 9 2]]


In [28]:
# Subarrays as no-copy views

arr = np.random.randint(10,size=(3,4))
print(arr,'\n')

# copy()

arr_sub = arr.copy()
print(arr_sub,'\n')

arr_sub[0,0]=99
print(arr,'\n', arr_sub)

[[0 3 0 3]
 [6 1 9 2]
 [9 4 9 1]] 

[[0 3 0 3]
 [6 1 9 2]
 [9 4 9 1]] 

[[0 3 0 3]
 [6 1 9 2]
 [9 4 9 1]] 
 [[99  3  0  3]
 [ 6  1  9  2]
 [ 9  4  9  1]]


In [42]:
# Reshapong of Arrays

arr = np.arange(9)
print(arr)

arr_new = arr.reshape(3,3)
print(arr_new)


# np.newaxis

arr_new_2= arr[np.newaxis,:]
print(arr_new_2)
print("ndim",arr_new_2.ndim)
print("ndim",arr_new_2.shape)
arr_new_3= arr[:,np.newaxis,]
print(arr_new_3)
print("ndim",arr_new_3.ndim)
print("ndim",arr_new_3.shape)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2 3 4 5 6 7 8]]
ndim 2
ndim (1, 9)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
ndim 2
ndim (9, 1)


In [51]:
# Array Concatenation

arr1= np.random.randint(10,size=(3,3))
print(arr1)
arr2= np.random.randint(10,size=(3,3))
print(arr2)
arr3= np.random.randint(10,size=(3,3))
print(arr3)

arr_total = np.concatenate([arr1,arr2,arr3],axis=1)
print(arr_total)


# vstack 종방향으로 연결

arr_total = np.vstack([arr1,arr2,arr3])
print(arr_total)


# hstack 횡방향으로 연결

arr_total = np.hstack([arr1,arr2,arr3])
print(arr_total)


[[2 4 9]
 [0 6 9]
 [2 4 7]]
[[3 0 5]
 [4 0 2]
 [3 1 7]]
[[1 3 4]
 [1 7 4]
 [0 2 7]]
[[2 4 9 3 0 5 1 3 4]
 [0 6 9 4 0 2 1 7 4]
 [2 4 7 3 1 7 0 2 7]]
[[2 4 9]
 [0 6 9]
 [2 4 7]
 [3 0 5]
 [4 0 2]
 [3 1 7]
 [1 3 4]
 [1 7 4]
 [0 2 7]]
[[2 4 9 3 0 5 1 3 4]
 [0 6 9 4 0 2 1 7 4]
 [2 4 7 3 1 7 0 2 7]]


In [55]:
# Array Splitting

arr = [1,2,3,99,99,3,2,1]

print(arr,'\n')

arr_1,arr_2,arr_3 = np.split(arr,[3,5])
print(arr_1,arr_2,arr_3 )


[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3] [99 99] [3 2 1]
