In [1]:
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
"""
Computing reciprocals in loops
"""

# Funtion for Computing reciprocals using loops

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output

values = np.random.randint(1,10,size = 5)
print(values)

[7 6 1 6 4]


In [4]:
"""
Comparison : loop vs ufunce(vectorized)
"""
big_arrays = np.random.randint(1,10,size=1000000)

# Looping on a big array

# jupyter magic function

%timeit compute_reciprocals(big_arrays)

1.68 s ± 39.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
# Vectorized opreotions

%timeit 1 / big_arrays

2.57 ms ± 151 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1  = np.random.randint(10, size=5)
arr2  = np.random.randint(10, size=5)
print(arr1,arr2)

arr1= arr1 -2
print(arr1,arr2)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10,size=(3,5))
print(arr4)

arr5 = arr4 **2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2] [0 1 7 6 9]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [16]:
"""
Ufuncs : Absolute Value
"""

x = np.array([-2,-1,0,1,2])
print(np.abs(x))

x = np.array([3-4j,4-3j,0,1,2])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 0. 1. 2.]


In [21]:
"""
Ufuncs : Trigonometrin Functions
"""

theta = np.linspace(0,np.pi,3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x= np.linspace(0,100,10)
print(x)

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [26]:
"""
UFuncs: Aggregation
"""

x = np.arange(1,5)
print(x)
accum = np.add.reduce(x)
print(accum)

accum = np.multiply.reduce(x)
print(accum)

accum = np.add.accumulate(x)
print(accum)

accum = np.multiply.accumulate(x)
print(accum)

[1 2 3 4]
10
24
[ 1  3  6 10]
[ 1  2  6 24]


In [33]:
"""
Summing the Values in an Array
"""

arr = np.random.rand(1000000)
np.sum(arr)

%timeit sum(arr)

%timeit np.sum(arr)


82 ms ± 4.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
405 µs ± 15.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [34]:
"""
Other Aggregation Function
"""

print("max ",np.max(arr))
print("min ",np.min(arr))
print("mean ",np.mean(arr))
print("median ", np.median(arr))
print("percentile ",np.percentile(arr,90))

print(np.any(arr>1))
print(np.all(arr>0))

max  0.9999994402748221
min  2.685856454354152e-06
mean  0.49974792232150633
median  0.499478384573658
percentile  0.9001509136077395
False
True


In [37]:
# Multi Dimensional Aggregates


np.random.seed(5)
arr = np.random.randint(10,size = (3,4))
print(arr)
print(np.sum(arr,axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[15 28  8]
