In [2]:
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
"""
numpy.concatenate
"""

x = [1,2,3]

y = [4,5,6]

z = [7,8,9]

np.concatenate([x,y,z])

# vstack() :  concatenate vertically

# hstack() :  concatenate 

print(np.vstack([x,y,z]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
"""
    pandas.concat()
"""

ser1 = pd.Series(["A",'B',"c"], index = [1,2,3])

ser2 = pd.Series(["D",'E',"F"], index = [4,5,6])

pd.concat([ser1,ser1,ser2])

# simply concatenate the two Series objects


1    A
2    B
3    c
1    A
2    B
3    c
4    D
5    E
6    F
dtype: object

In [27]:
#make_df(): crate a DataFrame object
def make_df(cols, ind):
    data = {c: [str(c) +  str(i) for i in ind]
           for c in cols}
    return pd.DataFrame(data, ind)

print(make_df('ABC', [1,2]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


In [28]:
# Concatenate the two DataFrame
df1 = make_df ('AB',[1,2])
df2 = make_df ('AB',[3,4])

print(df1,"\n")
print(df2,"\n")

pd.concat([df1,df2])

    A   B
1  A1  B1
2  A2  B2 

    A   B
3  A3  B3
4  A4  B4 



A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [29]:
df3 = make_df('AB',[0,1])
df4 = make_df('CD',[0,1])

print(df3,'\n')
print(df4,'\n')

print(pd.concat([df3,df4],axis=0))

    A   B
0  A0  B0
1  A1  B1 

    C   D
0  C0  D0
1  C1  D1 

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1


In [30]:
"""
concate() Features
"""

# Case 1 : Duplicate indices

x= make_df('AB',[0,1])
y= make_df('AB',[2,3])

y.index = x.index

print(x,'\n')
print(y,'\n')

print(pd.concat([x,y]))

    A   B
0  A0  B0
1  A1  B1 

    A   B
0  A2  B2
1  A3  B3 

    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [31]:
# Case 2 : catching duplications as errors
try:
    pd.concat([x,y], verify_integrity = True)
    
except ValueError as e:
        print("ValueError: ", e)

ValueError:  Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


In [32]:
# Case 3 : Ignore the index

print(pd.concat([x,y], ignore_index=True))

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


In [33]:
# Case 4 : Adding multiindex keys (hierarchical indexing)

In [36]:
"""
    concat(): join options
"""

x = make_df('ABC', [1,2])
y = make_df('BCD', [3,4])

# default : outer join -> union

print(x, "\n ")
print(y, "\n")

print(pd.concat([x,y], join = 'inner'))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2 
 
    B   C   D
3  B3  C3  D3
4  B4  C4  D4 

    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [39]:
"""
    Join operations
"""

# Prepare the two DataFrame objacts

df1 = pd.DataFrame({'employee': ['Bpb','Jake','Lisa', 'Sue'],
                   'group' : ['Accountiong', 'Engineering', 'Emgineereing', 'HR']})

df2 = pd.DataFrame({'employee': ['Bpb','Jake','Lisa', 'Sue'],
                   'hire_data' : [2004,2008,2012,2014]})
                    
print(df1,'\n')
print(df2)

  employee         group
0      Bpb   Accountiong
1     Jake   Engineering
2     Lisa  Emgineereing
3      Sue            HR 

  employee  hire_data
0      Bpb       2004
1     Jake       2008
2     Lisa       2012
3      Sue       2014


In [45]:
# One - to - one joins

df3 = pd.merge(df1, df2)

print(df3)

  employee         group  hire_data
0      Bpb   Accountiong       2004
1     Jake   Engineering       2008
2     Lisa  Emgineereing       2012
3      Sue            HR       2014


In [49]:
# Many - to - one joins

df4 = pd.DataFrame({'group' : ['Accountiong', 'Engineering', 'HR'],
                    'supervisor' : ['Carly','Guido', 'Steve']})

print(df3,'\n')
print(df4,'\n')

pd.merge(df3,df4)   # df3 = left, df4 = right 

  employee         group  hire_data
0      Bpb   Accountiong       2004
1     Jake   Engineering       2008
2     Lisa  Emgineereing       2012
3      Sue            HR       2014 

         group supervisor
0  Accountiong      Carly
1  Engineering      Guido
2           HR      Steve 



employee        group  hire_data supervisor
0      Bpb  Accountiong       2004      Carly
1     Jake  Engineering       2008      Guido
2      Sue           HR       2014      Steve

In [52]:
# Many - to - many joins

df5 = pd.DataFrame({'group' : [ 'Accountiong', 'Accountiong',
                              'Engineering', 'Engineering',
                              'HR', 'HR'],
                   'skills' : ['math,', 'spreadsheets', 'coding',
                              'linux', ' spreadsheets', 'organizationg']})

print(df1, '\n')
print(df5, '\n')

print(pd.merge(df1,df5))

  employee         group
0      Bpb   Accountiong
1     Jake   Engineering
2     Lisa  Emgineereing
3      Sue            HR 

         group         skills
0  Accountiong          math,
1  Accountiong   spreadsheets
2  Engineering         coding
3  Engineering          linux
4           HR   spreadsheets
5           HR  organizationg 

  employee        group         skills
0      Bpb  Accountiong          math,
1      Bpb  Accountiong   spreadsheets
2     Jake  Engineering         coding
3     Jake  Engineering          linux
4      Sue           HR   spreadsheets
5      Sue           HR  organizationg


In [57]:
"""
    Specifying the merge Key
"""

# 'on' argument : use a common column as merge key

print(df1,'\n')

print(df2,'\n')

df1['age'] = pd.Series([20,42,37,25])
df2['age'] = pd.Series([37,20,42,25])

print(df1,'\n')

print(df2,'\n')

pd.merge(df1,df2,on = 'employee')

  employee         group  age
0      Bpb   Accountiong   20
1     Jake   Engineering   42
2     Lisa  Emgineereing   37
3      Sue            HR   25 

  employee  hire_data  age
0      Bpb       2004   37
1     Jake       2008   20
2     Lisa       2012   42
3      Sue       2014   25 

  employee         group  age
0      Bpb   Accountiong   20
1     Jake   Engineering   42
2     Lisa  Emgineereing   37
3      Sue            HR   25 

  employee  hire_data  age
0      Bpb       2004   37
1     Jake       2008   20
2     Lisa       2012   42
3      Sue       2014   25 



employee         group  age_x  hire_data  age_y
0      Bpb   Accountiong     20       2004     37
1     Jake   Engineering     42       2008     20
2     Lisa  Emgineereing     37       2012     42
3      Sue            HR     25       2014     25

In [63]:
# 'Left _on' and 'right_on' arguments:

df3 = pd.DataFrame({'name' :  ['Bob', 'jake', 'Lisa', "Sue"],
                    'salary' : [70000,80000,120000,90000]})

print(df1,'\n')
print(df3,'\n')

print(pd.merge(df1,df3,left_on = 'employee', right_on = 'name'))

  employee         group  age
0      Bpb   Accountiong   20
1     Jake   Engineering   42
2     Lisa  Emgineereing   37
3      Sue            HR   25 

   name  salary
0   Bob   70000
1  jake   80000
2  Lisa  120000
3   Sue   90000 

  employee         group  age  name  salary
0     Lisa  Emgineereing   37  Lisa  120000
1      Sue            HR   25   Sue   90000


In [70]:
print(df1,'\n')
print(df2,'\n')

df1a = df1.set_index('employee')
df2a = df2.set_index('employee')

print(df1a,'\n')
print(df2a,'\n')


print(pd.merge(df1a,df2a, left_index = True, right_index = True) )

  employee         group  age
0      Bpb   Accountiong   20
1     Jake   Engineering   42
2     Lisa  Emgineereing   37
3      Sue            HR   25 

  employee  hire_data  age
0      Bpb       2004   37
1     Jake       2008   20
2     Lisa       2012   42
3      Sue       2014   25 

                 group  age
employee                   
Bpb        Accountiong   20
Jake       Engineering   42
Lisa      Emgineereing   37
Sue                 HR   25 

          hire_data  age
employee                
Bpb            2004   37
Jake           2008   20
Lisa           2012   42
Sue            2014   25 

                 group  age_x  hire_data  age_y
employee                                       
Bpb        Accountiong     20       2004     37
Jake       Engineering     42       2008     20
Lisa      Emgineereing     37       2012     42
Sue                 HR     25       2014     25
